apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: toggle-master-secrets-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: toggle-master-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: toggle-master-secrets-store
    kind: SecretStore
  target:
    name: toggle-master-secrets
  dataFrom:
    - extract:
        key: toggle-master/staging/application
