apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: toggle-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/analytics-service:latest
          ports:
            - containerPort: 8005
          env:
            - name: PORT
              value: "8005"
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: toggle-master-config
                  key: AWS_REGION
            - name: AWS_SQS_URL
              valueFrom:
                secretKeyRef:
                  name: toggle-master-secrets
                  key: AWS_SQS_URL
            - name: AWS_DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: toggle-master-config
                  key: AWS_DYNAMODB_TABLE
          resources:
            requests:
              cpu: "128m"
              memory: "128Mi"
            limits:
              cpu: "256m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: toggle-master
spec:
  selector:
    app: analytics-service
  ports:
    - port: 8005
      targetPort: 8005
  type: ClusterIP
