apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: toggle-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:latest
          ports:
            - containerPort: 8004
          env:
            - name: PORT
              value: "8004"
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: toggle-master-secrets
                  key: REDIS_URL
            - name: FLAG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: toggle-master-config
                  key: FLAG_SERVICE_URL
            - name: TARGETING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: toggle-master-config
                  key: TARGETING_SERVICE_URL
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: toggle-master-secrets
                  key: SERVICE_API_KEY
            - name: AWS_SQS_URL
              valueFrom:
                secretKeyRef:
                  name: toggle-master-secrets
                  key: AWS_SQS_URL
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: toggle-master-config
                  key: AWS_REGION
          resources:
            requests:
              cpu: "128m"
              memory: "128Mi"
            limits:
              cpu: "256m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: toggle-master
spec:
  selector:
    app: evaluation-service
  ports:
    - port: 8004
      targetPort: 8004
  type: ClusterIP
