apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toggle-master
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rogesson/toggle-master-terraform.git
    targetRevision: main
    path: gitops/base
  destination:
    server: https://kubernetes.default.svc
    namespace: toggle-master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
